<a href="https://colab.research.google.com/github/Tannusangwan22/superstore-powerbi-dashboard/blob/main/superstore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
df = pd.read_excel("superstore.xls")
df.head()


df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [8]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

In [9]:
df.dtypes

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
Country/Region            object
City                      object
State/Province            object
Postal Code               object
Region                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
dtype: object

In [10]:
# Delivery Time (in days)
df['Delivery Time'] = (df['Ship Date'] - df['Order Date']).dt.days

In [11]:
# Profit Ratio
df['Profit Ratio'] = df['Profit'] / df['Sales']

In [13]:
# Extract Year and Month
df['Order Year'] = df['Order Date'].dt.year
df['Order Month'] = df['Order Date'].dt.month

In [14]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Delivery Time,Profit Ratio,Order Year,Order Month
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512,4,0.3375,2023,1
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,4,-1.5500,2023,1
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Labels,Avery 508,11.784,3,0.2,4.2717,4,0.3625,2023,1
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748,4,-0.2375,2023,1
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840,7,0.2500,2023,1

In [15]:
# Total Sales and Profit
total_sales = df['Sales'].sum()
total_profit = df['Profit'].sum()

print("Total Sales:", total_sales)
print("Total Profit:", total_profit)

Total Sales: 2326534.3543
Total Profit: 292296.8145999999

In [16]:
df.groupby('Category')[['Sales', 'Profit']].sum()

                       Sales       Profit
Category
Furniture        754747.7613   19729.9956
Office Supplies  731893.3140  126023.4434
Technology       839893.2790  146543.3756

In [17]:
loss_data = df[df['Profit'] < 0]
loss_data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Delivery Time,Profit Ratio,Order Year,Order Month
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,4,-1.550000,2023,1
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748,4,-0.237500,2023,1
14,15,US-2023-105417,2023-01-07,2023-01-12,Standard Class,VS-21820,Vivek Sundaresam,Consumer,United States,Huntsville,...,Furnishings,"Howard Miller 14-1/2"" Diameter Chrome Round Wa...",76.728,3,0.6,-53.7096,5,-0.700000,2023,1
15,16,US-2023-105417,2023-01-07,2023-01-12,Standard Class,VS-21820,Vivek Sundaresam,Consumer,United States,Huntsville,...,Binders,Acco Four Pocket Poly Ring Binder with Label H...,10.430,7,0.8,-18.2525,5,-1.750000,2023,1
24,25,US-2023-118192,2023-01-13,2023-01-18,Standard Class,MM-17920,Michael Moore,Consumer,United States,Newark,...,Binders,Avery Metallic Poly Binders,3.438,2,0.7,-2.5212,5,-0.733333,2023,1

In [18]:
loss_data.groupby('Sub-Category')[['Sales', 'Profit']].sum().sort_values(by='Profit')

                    Sales      Profit
Sub-Category
Binders        36200.5010 -38563.4860
Tables        105699.3760 -32503.6583
Machines       72456.2530 -30118.6682
Bookcases      48217.3288 -12349.8096
Chairs         93460.1680 -10135.0373
Appliances      3382.5340  -8629.6412
Phones         35797.8400  -7530.6235
Furnishings    13293.4840  -6686.6785
Storage        38429.1440  -6480.2220
Supplies       14067.1760  -3015.6219
Accessories    10958.8000   -930.6265
Fasteners        149.2800    -33.1952
Labels            82.9200    -31.3860
Art               39.9600    -23.9760
Paper             14.0000     -6.3000

In [19]:
df.to_csv("superstore_cleaned.csv", index=False)